/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel.perfil'
import { Route as AuthenticatedPainelDiagnosticoRouteImport } from './routes/_authenticated/painel.diagnostico'
import { Route as AuthenticatedPainelAdminRouteImport } from './routes/_authenticated/painel.admin'
import { Route as AuthenticatedPainelAdminIndexRouteImport } from './routes/_authenticated/painel.admin.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedPainelAdminWebsiteRouteImport } from './routes/_authenticated/painel.admin.website'
import { Route as AuthenticatedPainelAdminUsuariosRouteImport } from './routes/_authenticated/painel.admin.usuarios'
import { Route as AuthenticatedPainelAdminLeadsRouteImport } from './routes/_authenticated/painel.admin.leads'
import { Route as AuthenticatedPainelAdminConfiguracoesRouteImport } from './routes/_authenticated/painel.admin.configuracoes'
import { Route as AuthenticatedPainelAdminWebsiteIndexRouteImport } from './routes/_authenticated/painel.admin.website.index'
import { Route as AuthenticatedPainelAdminWebsiteBlogpostsRouteImport } from './routes/_authenticated/painel.admin.website.blogposts'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDiagnosticoRoute =
  AuthenticatedPainelDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminRoute =
  AuthenticatedPainelAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminIndexRoute =
  AuthenticatedPainelAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPainelAdminWebsiteRoute =
  AuthenticatedPainelAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminUsuariosRoute =
  AuthenticatedPainelAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminLeadsRoute =
  AuthenticatedPainelAdminLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminConfiguracoesRoute =
  AuthenticatedPainelAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminWebsiteIndexRoute =
  AuthenticatedPainelAdminWebsiteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelAdminWebsiteRoute,
  } as any)
const AuthenticatedPainelAdminWebsiteBlogpostsRoute =
  AuthenticatedPainelAdminWebsiteBlogpostsRouteImport.update({
    id: '/blogposts',
    path: '/blogposts',
    getParentRoute: () => AuthenticatedPainelAdminWebsiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/painel/admin': typeof AuthenticatedPainelAdminRouteWithChildren
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/painel/admin/website': typeof AuthenticatedPainelAdminWebsiteRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/painel/admin/': typeof AuthenticatedPainelAdminIndexRoute
  '/painel/admin/website/blogposts': typeof AuthenticatedPainelAdminWebsiteBlogpostsRoute
  '/painel/admin/website/': typeof AuthenticatedPainelAdminWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/painel/admin': typeof AuthenticatedPainelAdminIndexRoute
  '/painel/admin/website/blogposts': typeof AuthenticatedPainelAdminWebsiteBlogpostsRoute
  '/painel/admin/website': typeof AuthenticatedPainelAdminWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/painel/admin': typeof AuthenticatedPainelAdminRouteWithChildren
  '/_authenticated/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/_authenticated/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/_authenticated/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/_authenticated/painel/admin/website': typeof AuthenticatedPainelAdminWebsiteRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/painel/admin/': typeof AuthenticatedPainelAdminIndexRoute
  '/_authenticated/painel/admin/website/blogposts': typeof AuthenticatedPainelAdminWebsiteBlogpostsRoute
  '/_authenticated/painel/admin/website/': typeof AuthenticatedPainelAdminWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/painel'
    | '/email/unsubscribe'
    | '/painel/admin'
    | '/painel/diagnostico'
    | '/painel/perfil'
    | '/lovable/email/suppression'
    | '/painel/'
    | '/painel/admin/configuracoes'
    | '/painel/admin/leads'
    | '/painel/admin/usuarios'
    | '/painel/admin/website'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/painel/admin/'
    | '/painel/admin/website/blogposts'
    | '/painel/admin/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/email/unsubscribe'
    | '/painel/diagnostico'
    | '/painel/perfil'
    | '/lovable/email/suppression'
    | '/painel'
    | '/painel/admin/configuracoes'
    | '/painel/admin/leads'
    | '/painel/admin/usuarios'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/painel/admin'
    | '/painel/admin/website/blogposts'
    | '/painel/admin/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnostico'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/email/unsubscribe'
    | '/_authenticated/painel/admin'
    | '/_authenticated/painel/diagnostico'
    | '/_authenticated/painel/perfil'
    | '/lovable/email/suppression'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/admin/configuracoes'
    | '/_authenticated/painel/admin/leads'
    | '/_authenticated/painel/admin/usuarios'
    | '/_authenticated/painel/admin/website'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/painel/admin/'
    | '/_authenticated/painel/admin/website/blogposts'
    | '/_authenticated/painel/admin/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/diagnostico': {
      id: '/_authenticated/painel/diagnostico'
      path: '/diagnostico'
      fullPath: '/painel/diagnostico'
      preLoaderRoute: typeof AuthenticatedPainelDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/admin': {
      id: '/_authenticated/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof AuthenticatedPainelAdminRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/admin/': {
      id: '/_authenticated/painel/admin/'
      path: '/'
      fullPath: '/painel/admin/'
      preLoaderRoute: typeof AuthenticatedPainelAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/admin/website': {
      id: '/_authenticated/painel/admin/website'
      path: '/website'
      fullPath: '/painel/admin/website'
      preLoaderRoute: typeof AuthenticatedPainelAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/usuarios': {
      id: '/_authenticated/painel/admin/usuarios'
      path: '/usuarios'
      fullPath: '/painel/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedPainelAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/leads': {
      id: '/_authenticated/painel/admin/leads'
      path: '/leads'
      fullPath: '/painel/admin/leads'
      preLoaderRoute: typeof AuthenticatedPainelAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/configuracoes': {
      id: '/_authenticated/painel/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/website/': {
      id: '/_authenticated/painel/admin/website/'
      path: '/'
      fullPath: '/painel/admin/website/'
      preLoaderRoute: typeof AuthenticatedPainelAdminWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedPainelAdminWebsiteRoute
    }
    '/_authenticated/painel/admin/website/blogposts': {
      id: '/_authenticated/painel/admin/website/blogposts'
      path: '/blogposts'
      fullPath: '/painel/admin/website/blogposts'
      preLoaderRoute: typeof AuthenticatedPainelAdminWebsiteBlogpostsRouteImport
      parentRoute: typeof AuthenticatedPainelAdminWebsiteRoute
    }
  }
}

interface AuthenticatedPainelAdminWebsiteRouteChildren {
  AuthenticatedPainelAdminWebsiteBlogpostsRoute: typeof AuthenticatedPainelAdminWebsiteBlogpostsRoute
  AuthenticatedPainelAdminWebsiteIndexRoute: typeof AuthenticatedPainelAdminWebsiteIndexRoute
}

const AuthenticatedPainelAdminWebsiteRouteChildren: AuthenticatedPainelAdminWebsiteRouteChildren =
  {
    AuthenticatedPainelAdminWebsiteBlogpostsRoute:
      AuthenticatedPainelAdminWebsiteBlogpostsRoute,
    AuthenticatedPainelAdminWebsiteIndexRoute:
      AuthenticatedPainelAdminWebsiteIndexRoute,
  }

const AuthenticatedPainelAdminWebsiteRouteWithChildren =
  AuthenticatedPainelAdminWebsiteRoute._addFileChildren(
    AuthenticatedPainelAdminWebsiteRouteChildren,
  )

interface AuthenticatedPainelAdminRouteChildren {
  AuthenticatedPainelAdminConfiguracoesRoute: typeof AuthenticatedPainelAdminConfiguracoesRoute
  AuthenticatedPainelAdminLeadsRoute: typeof AuthenticatedPainelAdminLeadsRoute
  AuthenticatedPainelAdminUsuariosRoute: typeof AuthenticatedPainelAdminUsuariosRoute
  AuthenticatedPainelAdminWebsiteRoute: typeof AuthenticatedPainelAdminWebsiteRouteWithChildren
  AuthenticatedPainelAdminIndexRoute: typeof AuthenticatedPainelAdminIndexRoute
}

const AuthenticatedPainelAdminRouteChildren: AuthenticatedPainelAdminRouteChildren =
  {
    AuthenticatedPainelAdminConfiguracoesRoute:
      AuthenticatedPainelAdminConfiguracoesRoute,
    AuthenticatedPainelAdminLeadsRoute: AuthenticatedPainelAdminLeadsRoute,
    AuthenticatedPainelAdminUsuariosRoute:
      AuthenticatedPainelAdminUsuariosRoute,
    AuthenticatedPainelAdminWebsiteRoute:
      AuthenticatedPainelAdminWebsiteRouteWithChildren,
    AuthenticatedPainelAdminIndexRoute: AuthenticatedPainelAdminIndexRoute,
  }

const AuthenticatedPainelAdminRouteWithChildren =
  AuthenticatedPainelAdminRoute._addFileChildren(
    AuthenticatedPainelAdminRouteChildren,
  )

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAdminRoute: typeof AuthenticatedPainelAdminRouteWithChildren
  AuthenticatedPainelDiagnosticoRoute: typeof AuthenticatedPainelDiagnosticoRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAdminRoute: AuthenticatedPainelAdminRouteWithChildren,
  AuthenticatedPainelDiagnosticoRoute: AuthenticatedPainelDiagnosticoRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
