/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelDiagnosticoRouteImport } from './routes/_authenticated/painel.diagnostico'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelDiagnosticoRoute =
  AuthenticatedPainelDiagnosticoRouteImport.update({
    id: '/painel/diagnostico',
    path: '/painel/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/painel/diagnostico'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/painel/diagnostico'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnostico'
    | '/_authenticated/admin'
    | '/_authenticated/painel/diagnostico'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/diagnostico': {
      id: '/_authenticated/painel/diagnostico'
      path: '/painel/diagnostico'
      fullPath: '/painel/diagnostico'
      preLoaderRoute: typeof AuthenticatedPainelDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelDiagnosticoRoute: typeof AuthenticatedPainelDiagnosticoRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelDiagnosticoRoute: AuthenticatedPainelDiagnosticoRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoRoute: DiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
