/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelPerfilRouteImport } from './routes/_authenticated/painel.perfil'
import { Route as AuthenticatedPainelDiagnosticoRouteImport } from './routes/_authenticated/painel.diagnostico'
import { Route as AuthenticatedPainelAdminRouteImport } from './routes/_authenticated/painel.admin'
import { Route as AuthenticatedPainelAdminIndexRouteImport } from './routes/_authenticated/painel.admin.index'
import { Route as AuthenticatedPainelAdminUsuariosRouteImport } from './routes/_authenticated/painel.admin.usuarios'
import { Route as AuthenticatedPainelAdminLeadsRouteImport } from './routes/_authenticated/painel.admin.leads'
import { Route as AuthenticatedPainelAdminConfiguracoesRouteImport } from './routes/_authenticated/painel.admin.configuracoes'

const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPerfilRoute =
  AuthenticatedPainelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDiagnosticoRoute =
  AuthenticatedPainelDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminRoute =
  AuthenticatedPainelAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminIndexRoute =
  AuthenticatedPainelAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminUsuariosRoute =
  AuthenticatedPainelAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminLeadsRoute =
  AuthenticatedPainelAdminLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)
const AuthenticatedPainelAdminConfiguracoesRoute =
  AuthenticatedPainelAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedPainelAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/painel/admin': typeof AuthenticatedPainelAdminRouteWithChildren
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/painel/admin/': typeof AuthenticatedPainelAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/painel/admin': typeof AuthenticatedPainelAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/painel/admin': typeof AuthenticatedPainelAdminRouteWithChildren
  '/_authenticated/painel/diagnostico': typeof AuthenticatedPainelDiagnosticoRoute
  '/_authenticated/painel/perfil': typeof AuthenticatedPainelPerfilRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/admin/configuracoes': typeof AuthenticatedPainelAdminConfiguracoesRoute
  '/_authenticated/painel/admin/leads': typeof AuthenticatedPainelAdminLeadsRoute
  '/_authenticated/painel/admin/usuarios': typeof AuthenticatedPainelAdminUsuariosRoute
  '/_authenticated/painel/admin/': typeof AuthenticatedPainelAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/painel'
    | '/painel/admin'
    | '/painel/diagnostico'
    | '/painel/perfil'
    | '/painel/'
    | '/painel/admin/configuracoes'
    | '/painel/admin/leads'
    | '/painel/admin/usuarios'
    | '/painel/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/admin'
    | '/painel/diagnostico'
    | '/painel/perfil'
    | '/painel'
    | '/painel/admin/configuracoes'
    | '/painel/admin/leads'
    | '/painel/admin/usuarios'
    | '/painel/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnostico'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/_authenticated/painel/admin'
    | '/_authenticated/painel/diagnostico'
    | '/_authenticated/painel/perfil'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/admin/configuracoes'
    | '/_authenticated/painel/admin/leads'
    | '/_authenticated/painel/admin/usuarios'
    | '/_authenticated/painel/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/perfil': {
      id: '/_authenticated/painel/perfil'
      path: '/perfil'
      fullPath: '/painel/perfil'
      preLoaderRoute: typeof AuthenticatedPainelPerfilRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/diagnostico': {
      id: '/_authenticated/painel/diagnostico'
      path: '/diagnostico'
      fullPath: '/painel/diagnostico'
      preLoaderRoute: typeof AuthenticatedPainelDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/admin': {
      id: '/_authenticated/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof AuthenticatedPainelAdminRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/admin/': {
      id: '/_authenticated/painel/admin/'
      path: '/'
      fullPath: '/painel/admin/'
      preLoaderRoute: typeof AuthenticatedPainelAdminIndexRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/usuarios': {
      id: '/_authenticated/painel/admin/usuarios'
      path: '/usuarios'
      fullPath: '/painel/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedPainelAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/leads': {
      id: '/_authenticated/painel/admin/leads'
      path: '/leads'
      fullPath: '/painel/admin/leads'
      preLoaderRoute: typeof AuthenticatedPainelAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
    '/_authenticated/painel/admin/configuracoes': {
      id: '/_authenticated/painel/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/painel/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedPainelAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedPainelAdminRoute
    }
  }
}

interface AuthenticatedPainelAdminRouteChildren {
  AuthenticatedPainelAdminConfiguracoesRoute: typeof AuthenticatedPainelAdminConfiguracoesRoute
  AuthenticatedPainelAdminLeadsRoute: typeof AuthenticatedPainelAdminLeadsRoute
  AuthenticatedPainelAdminUsuariosRoute: typeof AuthenticatedPainelAdminUsuariosRoute
  AuthenticatedPainelAdminIndexRoute: typeof AuthenticatedPainelAdminIndexRoute
}

const AuthenticatedPainelAdminRouteChildren: AuthenticatedPainelAdminRouteChildren =
  {
    AuthenticatedPainelAdminConfiguracoesRoute:
      AuthenticatedPainelAdminConfiguracoesRoute,
    AuthenticatedPainelAdminLeadsRoute: AuthenticatedPainelAdminLeadsRoute,
    AuthenticatedPainelAdminUsuariosRoute:
      AuthenticatedPainelAdminUsuariosRoute,
    AuthenticatedPainelAdminIndexRoute: AuthenticatedPainelAdminIndexRoute,
  }

const AuthenticatedPainelAdminRouteWithChildren =
  AuthenticatedPainelAdminRoute._addFileChildren(
    AuthenticatedPainelAdminRouteChildren,
  )

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAdminRoute: typeof AuthenticatedPainelAdminRouteWithChildren
  AuthenticatedPainelDiagnosticoRoute: typeof AuthenticatedPainelDiagnosticoRoute
  AuthenticatedPainelPerfilRoute: typeof AuthenticatedPainelPerfilRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAdminRoute: AuthenticatedPainelAdminRouteWithChildren,
  AuthenticatedPainelDiagnosticoRoute: AuthenticatedPainelDiagnosticoRoute,
  AuthenticatedPainelPerfilRoute: AuthenticatedPainelPerfilRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoRoute: DiagnosticoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
